### ISSUE TITLE
Shipping rates

### ISSUE THREAD

**Issue by jpratt** [tiamo/magento2-applepay#2]
Great module. One issue I am having is on the applepay/payment/review screen coming in from the shopping cart, it is not getting any shipping rates. I have the store setup to use default tablerates and regular checkout returns rates fine, but cannot proceed as this page does not return any rates. Ideas?

**Comment by tiamo** [comment]
What version of magento do you use?

**Comment by jpratt** [comment]
We are on 2.1.9.

**Comment by jpratt** [comment]
@tiamo See #3 the country code was lowercase from applepay so the country code could not be used when getting rates. This can be closed with that pull request. Thanks!

**Comment by tiamo** [comment]
Thanks for your contribution.
